add_rules("mode.debug", "mode.release")
set_languages("c++20")
-- add_requires("muslcc")
-- set_toolchains("@muslcc")

set_version("0.1.6", {build = "%Y%m%d%H%M"})

-- add_repositories("local- repo /doc/code/PROJECTS/tinge/build")
-- add_requires("tinge")
add_requires("opencv", {system = true})
add_requires("eigen", {system = false})
add_requires("fmt", {system = false})
add_requires("spdlog", {system = false}) 
-- add_requires("openblas", {system = false})
-- add_requires("armadillo", {system = false})
 
target("run")
    set_kind("binary")
    add_includedirs("include")
    add_files("src/*.cpp")
    -- add_packages("tinge", {config = {static = true}})
    add_packages("opencv")
    add_packages("eigen")
    add_packages("fmt")
    add_packages("spdlog")
    -- add_packages("armadillo")