add_rules("mode.debug", "mode.release")

set_languages("c++20")

add_requires("opencv", {system = true})
add_requires("eigen", {system = true})
add_requires("fmt", {system = true})
add_requires("spdlog", {system = true})

-- target("inference")
--     set_kind("static")
--     add_includedirs("include")
--     add_files("src/*.cpp")
--     add_packages("opencv")

-- target("standalone")
--     set_kind("binary")
--     add_files("src/standalone.cpp")
--     add_packages("opencv")
--     add_includedirs("include")

target("run")
    -- add_deps("inference")
    set_kind("binary")
    add_includedirs("include")
    add_files("src/*.cpp")
    -- add_files("src/inference.cpp")
    add_packages("opencv")
    add_packages("eigen")
    add_packages("fmt")
    add_packages("spdlog")